### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by alex-tan** [stoeffel/elmi-to-json#39]
Noticed that I wasn't able to install some dependencies in one of the projects I work on but also I'm unable to install the dependency directly either.

`yarn global add elmi-to-json` produces:

```bash
yarn global v1.22.10
[1/4] 🔍  Resolving packages...
warning elmi-to-json > binwrap > request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning elmi-to-json > binwrap > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning elmi-to-json > binwrap > request > har-validator@5.1.5: this library is no longer supported
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/alextan/.config/yarn/global/node_modules/elmi-to-json: Command failed.
Exit code: 1
Command: binwrap-install
Arguments: 
Directory: /Users/alextan/.config/yarn/global/node_modules/elmi-to-json
Output:
/Users/alextan/.config/yarn/global/node_modules/binwrap/install.js:18
    throw new Error("No binaries are available for your platform: " + buildId);
    ^

Error: No binaries are available for your platform: darwin-arm64
    at install (/Users/alextan/.config/yarn/global/node_modules/binwrap/install.js:18:11)
    at Object.install (/Users/alextan/.config/yarn/global/node_modules/binwrap/index.js:14:14)
    at Object.<anonymous> (/Users/alextan/.config/yarn/global/node_modules/binwrap/bin/binwrap-install:18:9)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

Happy to help test out if the package is updated for this platform.

**Comment by avh4** [comment]
I just did a similar fix for elm-format (https://github.com/avh4/elm-format/issues/722), and I'd expect the change to be adding a mapping for darwin-arm64 here (for the moment at least, the new Macs are able to run the x64 binaries):

https://github.com/stoeffel/elmi-to-json/blob/master/index.js#L17
```
    "darwin-arm64": root + "-osx.tar.gz",
```


(As for actually building arm64 binaries, there are several upstream issues that I'm tracking for elm-format here: https://github.com/avh4/elm-format/issues/723)
